name: flutter_mock_firebase_auth
description: "Illustrate use of Firebase Auth mocking."

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.14.0

  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.9
  intl: ^0.19.0
  riverpod_annotation: 2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.7
  integration_test:
    sdk: flutter
  patrol_finders: ^2.1.2
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0


flutter:
  uses-material-design: true
