// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0q-ezj1Q7Jr6NNenpAd3-qB4FnLcTQbc',
    appId: '1:134763466334:web:b58aa20f27e48ba54feecf',
    messagingSenderId: '134763466334',
    projectId: 'flutter-mock-firebase-auth',
    authDomain: 'flutter-mock-firebase-auth.firebaseapp.com',
    storageBucket: 'flutter-mock-firebase-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLjazDqeZbki5Usf6_0uAUSla9c25-mkM',
    appId: '1:134763466334:android:51244bc34e4b988c4feecf',
    messagingSenderId: '134763466334',
    projectId: 'flutter-mock-firebase-auth',
    storageBucket: 'flutter-mock-firebase-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdDkmSo65mDR2ALpUXR_Ft3pVwg7HV1g',
    appId: '1:134763466334:ios:43a9d06956f93fa94feecf',
    messagingSenderId: '134763466334',
    projectId: 'flutter-mock-firebase-auth',
    storageBucket: 'flutter-mock-firebase-auth.appspot.com',
    iosBundleId: 'com.example.flutterMockFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdDkmSo65mDR2ALpUXR_Ft3pVwg7HV1g',
    appId: '1:134763466334:ios:43a9d06956f93fa94feecf',
    messagingSenderId: '134763466334',
    projectId: 'flutter-mock-firebase-auth',
    storageBucket: 'flutter-mock-firebase-auth.appspot.com',
    iosBundleId: 'com.example.flutterMockFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0q-ezj1Q7Jr6NNenpAd3-qB4FnLcTQbc',
    appId: '1:134763466334:web:ef1d716dcb4a4d2b4feecf',
    messagingSenderId: '134763466334',
    projectId: 'flutter-mock-firebase-auth',
    authDomain: 'flutter-mock-firebase-auth.firebaseapp.com',
    storageBucket: 'flutter-mock-firebase-auth.appspot.com',
  );
}
